[project]
name = "projectagenticagpr"
version = "0.1.0"
description = "This is a project for Agentica's GDPR compliance. "
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi[standard]>=0.115.12",
]
